name: CD
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Build Docker image
        run: docker build -t gameroasters/protobuf-unity:${{ steps.get_version.outputs.version }} -f Dockerfile .

      - name: Extract .net DLL zip
        run: make pr-dlls-zip

      - uses: actions/upload-artifact@v1
        with:
          name: protobuf_unity_dlls.zip
          path: ./zip/protobuf_unity_dlls.zip

      - name: Login to Docker Hub
        run: |
          docker login \
          -u ${{ secrets.DOCKER_USERNAME }} \
          -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker image
        run: docker push gameroasters/protobuf-unity:${{ steps.get_version.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-') }}
          files: |
            ./dlls/protobuf_unity_dlls.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
