name: CI
on:
  schedule:
    - cron: "0 1 * * *" # run at 2 AM UTC
  push:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   run: |
      #     docker login \
      #     -u ${{ secrets.DOCKER_USERNAME }} \
      #     -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: make build

      - name: Extract .net DLL
        run: make pr-dlls-zip

      - uses: actions/upload-artifact@v1
        with:
          name: protobuf_unity_dlls.zip
          path: ./dlls/protobuf_unity_dlls.zip

      # - name: Publish Docker image
      #   run: docker push gameroasters/protobuf-unity:latest
